spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${URL_PROD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    initialize: true
