server:
  port: 8085

spring:
  application:
    name: SecurePro
  profiles:
    active: prod
  security:
    enabled: false
 

  # thymeleaf:
  #   cache: false
  #   prefix: classpath:/templates/
  #   suffix: .html

  # JPA Configuration
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.formations: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
