spring:
  config:
    activate:
      on-profile: dev

  liquibase:
      change-log: classpath:db/db.changelog-master.yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

  datasource:
    url: ${URL_DEV}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}