version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME_PROD}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD_PROD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME_PROD}
      PGUSER: ${DB_USERNAME_PROD}
      PGPASSWORD: ${ROOT_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD_PROD}
      POSTGRES_DB: ${DB_NAME_PROD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:
