version: '3.8'
services:
  shopapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securepro_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${URL_PROD}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME_PROD}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD_PROD}
      SPRING_DDL_AUTO: validate
      APP_PORT: ${APP_PORT}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DRIVER_NAME}
    depends_on:
      - db
    networks:
      - securepro_api

  db:
    image: mariadb:latest 
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: ${DB_NAME_PROD} 
      MYSQL_USER: ${DB_USERNAME_PROD} 
      MYSQL_PASSWORD: ${DB_PASSWORD_PROD} 
    ports:
      - "3306:3306" 
    networks:
      - securepro_api
    command:
      --bind-address=0.0.0.0  

volumes:
  mysql-data: 

networks:
  securepro_api:
    driver: bridge
